spring.application.name=campconnect
### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/CAMPCONNECT?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/campconnect
server.port=8085

